### ISSUE TITLE
Bug in function localizeddate for date 31 december

### ISSUE THREAD

**Issue by AlexBDev** [twigphp/Twig-extensions#135]
Hi, i have a recent issue with the localizeddate function on every date 31 december,  the function return the next year instead current year.

For example with the date 31/12/2015, pass to the function:

`date|localizeddate('long', 'none', "fr_FR", null,"dd MMMM Y")`

The function return 2016 for year.

When i use

`date|format_date`

The output is right.

Regards,
Alexis

**Comment by ksn135** [comment]
Confirm this issue !
In my config.yml:
```yaml
twig:
    date:
        timezone:         Europe/Moscow
```
In my template:
```twig
{{ '2015-05-28'|localizeddate }}
```
Expected: ```28 мая 2015 г., 0:00:00```
My result: ```28 мая 2015 г., 1:00:00``` (***plus one hour***!)

To workaround this issue set your timezone to "UTC" globally in config.yml:
```yaml
twig:
    date:
        timezone:        UTC
```
or locally in your controller
```php
        $this->get('twig')->getExtension('core')->setTimezone('UTC');        
```
