### ISSUE TITLE
Translator decorator error in prod

### ISSUE THREAD

**Issue by dvdknaap** [twigphp/Twig-extensions#244]
This package is broken since the laste translator proxy update in symfony 4

On production you get 'Arugment 1 passed to Twig_extensions_extension_date::__construct() must implement interface TranslatorDecorator'

On dev mode it's working.

services.yaml
```yml
    app.decorating_translator:
        class:     App\Service\Translator\TranslatorDecorator
        decorates: translator
        arguments:
            $translator: '@app.decorating_translator.inner' # original translator
        public:    false
```

src\Service\Translator\TranslatorDecorator
```php
<?php
namespace App\Service\Translator;

use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Translation\Exception\InvalidArgumentException;
use Symfony\Component\Translation\MessageCatalogueInterface;
use Symfony\Component\Translation\TranslatorBagInterface;
use Symfony\Contracts\Translation\LocaleAwareInterface;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Class TranslatorDecorator
 *
 * @package App\Service\Translator
 */
class TranslatorDecorator implements TranslatorInterface, TranslatorBagInterface, LocaleAwareInterface
{

}
```
This package has a lot of deprecation errors maybe an good idea to fix that to ?
