### ISSUE TITLE
Attempted to load class "Twig_Extensions_Extension_Intl"

### ISSUE THREAD

**Issue by pdias** [twigphp/Twig-extensions#250]
I'm using **Symfony 3.4.30**, with **twig/extensions** **dev-master**, in my **services.yml** i have this:

```
twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
```

now I catch this error:

```
Attempted to load class "Twig_Extensions_Extension_Intl" from the global na  
  mespace.                                                                     
  Did you forget a "use" statement?
```

I know this is probably from my configuration that this is wrong. Can you help me? Or is it not possible to use **dev-master**?
